import { Injectable } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import { Helper } from './shared/helpers';

@Injectable()
export class AppService {
  handleStuff() {
    const data = [
      {
        name: ' Automotive',
        parentId: '1',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623533577/zenzfriden6pazdubsg6.png',
      },
      { name: 'Automotive Leasing and Rental', subId: '1' },
      { name: 'Automotive Parts', subId: '1' },
      { name: 'Automotive Batteries', subId: '1' },
      { name: 'Automotive Body, Trim and Glass', subId: '1' },
      { name: 'Automotive Drivetrain and Transmission', subId: '1' },
      { name: 'Automotive Fuel Systems', subId: '1' },
      { name: 'Automotive Tires', subId: '1' },
      { name: 'Automotive Repair', subId: '1' },
      { name: 'Trucks', subId: '1' },
      { name: 'Electric and Hybrid Vehicles', subId: '1' },
      { name: 'Emergency Vehicles', subId: '1' },
      { name: 'Motorcycles', subId: '1' },
      { name: 'RVs and Mobile Homes', subId: '1' },
      { name: 'Used Vehicles', subId: '1' },
      { name: 'New Vehicles', subId: '1' },
      {
        name: 'Aerospace',
        parentId: '2',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623533627/jjfecfgqwhtaswhvapjt.png',
      },
      { name: 'Aircraft', subId: '2' },
      { name: 'Aircraft Parts', subId: '2' },
      { name: 'Airport Security Equipment', subId: '2' },
      { name: 'Aviation Freight and Cargo', subId: '2' },
      { name: 'Avionics', subId: '2' },
      { name: 'Space Systems, Satellites and Launchers', subId: '2' },
      { name: 'UAVs and Drones', subId: '2' },

      {
        name: 'Maritime',
        parentId: '3',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623533658/fnew8esiywf2ioawhnzo.png',
      },
      { name: 'Fishing Vessels and Equipment', subId: '3' },
      { name: 'Sea and Water Freight', subId: '3' },
      { name: 'Shipbuilding and Ship Parts', subId: '3' },
      {
        name: 'Rail',
        parentId: '4',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623533696/jrnjpr8lzy31oskyngl4.png',
      },
      { name: 'Rail Transport Vehicles', subId: '4' },
      { name: 'Railways Stations Equipment', subId: '4' },
      {
        name: 'Insurance',
        parentId: '5',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534503/e8grwrmzlnuwgcba3zfr.png',
      },
      { name: 'Automotive Insurance', subId: '5' },
      { name: 'Health Insurance', subId: '5' },
      { name: 'Life Insurance', subId: '5' },
      { name: 'Property Insurance', subId: '5' },
      { name: 'Reinsurance', subId: '5' },
      { name: 'Travel Insurance', subId: '5' },
      {
        name: ' Real Estate',
        parentId: '6',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534647/nou4mrah7juegoeomkin.png',
      },
      { name: 'Commercial Property – Sale', subId: '6' },
      { name: 'Commercial Property – Lease', subId: '6' },
      { name: 'Residential Property – Sale', subId: '6' },
      { name: 'Residential Property - Lease ', subId: '6' },
      { name: 'Lands and plots', subId: '6' },
      { name: 'Short Let', subId: '6' },
      { name: 'Event Centers', subId: '6' },
      { name: 'Venues', subId: '6' },
      { name: 'Workstations/Coworking Spaces', subId: '6' },
      {
        name: 'Chemicals',
        parentId: '7',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534708/iedxzn6x5trha5wgsei6.png',
      },
      { name: 'Adhesives and Sealants', subId: '7' },
      { name: 'Agrochemicals and Fertilizers', subId: '7' },
      { name: 'Catalysts', subId: '7' },
      { name: 'Chemicals - Cosmetic', subId: '7' },
      { name: 'Chemicals - Detergent', subId: '7' },
      { name: 'Disinfectants', subId: '7' },
      { name: 'Lubricants and Greases', subId: '7' },
      { name: 'Organic Acids', subId: '7' },
      { name: 'Paints and Coatings', subId: '7' },
      { name: 'Petrochemicals', subId: '7' },
      { name: 'Refrigerants', subId: '7' },
      { name: 'Silicones', subId: '7' },
      { name: 'Solvents', subId: '7' },
      { name: 'Water Treatment Chemicals', subId: '7' },

      {
        name: 'Wares',
        parentId: '8',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534766/m4sxwta9gdguq70y2cif.png',
      },
      { name: 'Glass', subId: '8' },
      { name: 'Ceramics', subId: '8' },
      { name: 'Other wares', subId: '8' },
      {
        name: 'Metals and Minerals',
        parentId: '9',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534813/hzpmppcvdolgn51l3cuf.png',
      },
      { name: 'Iron and Steel', subId: '9' },
      { name: 'Aluminum', subId: '9' },
      { name: 'Copper', subId: '9' },
      { name: 'Precious Metals', subId: '9' },
      { name: 'Salts', subId: '9' },
      { name: 'Wire and Cables', subId: '9' },
      { name: 'Nanomaterials', subId: '9' },
      {
        name: 'Packaging',
        parentId: '10',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623534906/nno7staa7uqoes0zy3n9.png',
      },
      { name: 'Food Packaging', subId: '10' },
      { name: 'Labels', subId: '10' },
      { name: 'Pharmaceutical Packaging', subId: '10' },
      { name: 'Plastic Packaging', subId: '10' },
      { name: 'Plastics', subId: '10' },
      { name: 'Pulp and Paper', subId: '10' },
      {
        name: 'Recycling and Recycled Materials',
        parentId: '11',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535034/jn4kx7h4lia4j9hvvhs9.png',
      },
      { name: 'Rubber', subId: '11' },
      { name: 'Textiles', subId: '11' },
      { name: 'Animal Textiles', subId: '11' },
      { name: 'Mineral Textiles', subId: '11' },
      { name: 'Plant Textiles', subId: '11' },
      { name: 'Synthetic Textiles', subId: '11' },
      { name: 'Technical Textiles', subId: '11' },
      { name: 'Wood and Wood Products', subId: '11' },
      { name: 'Arts and Crafts', subId: '11' },
      {
        name: 'Fashion',
        parentId: '12',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535389/z7odqsczn5mkxr2psxpa.png',
      },
      { name: 'Baby and Children’s wear', subId: '12' },
      { name: 'Footwear – Men', subId: '12' },
      { name: 'Footwear – Women', subId: '12' },
      { name: 'Handbags, Purses and Wallets', subId: '12' },
      { name: 'Jewelry and Watches', subId: '12' },
      { name: 'Luggage and Travel Bags', subId: '12' },
      { name: 'Menswear', subId: '12' },
      { name: 'Sportswear', subId: '12' },
      { name: 'Womenswear', subId: '12' },
      { name: 'Lingerie and Hosiery', subId: '12' },
      { name: 'Workwear', subId: '12' },
      { name: 'Eye Care and Eyewear', subId: '12' },
      {
        name: 'Consumer Electronics',
        parentId: '13',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535482/mr7nsbzhfqukui01rdqy.png',
      },
      { name: 'Music Equipment', subId: '13' },
      { name: 'Cameras and Equipment', subId: '13' },
      { name: 'Car Electronics and GPS', subId: '13' },
      { name: 'Computer Accessories', subId: '13' },
      { name: 'Desktop Computers', subId: '13' },
      { name: 'Laptops and Notebooks', subId: '13' },
      { name: 'Lighting Equipment', subId: '13' },
      { name: 'Smartphones and Mobile Devices', subId: '13' },
      { name: 'Tablets and E-Readers', subId: '13' },
      { name: 'Televisions', subId: '13' },
      { name: 'Video Games and Consoles', subId: '13' },
      { name: 'Wearable Technology', subId: '13' },
      { name: 'Household Appliances', subId: '13' },
      { name: 'Printers and Scanners', subId: '13' },
      { name: 'Headphones', subId: '13' },
      {
        name: 'Consumer Services and Utilities',
        parentId: '14',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535518/jezmly18ftmhgngobihf.png',
      },
      { name: 'Fitness and Health Centers', subId: '14' },
      { name: 'Florists', subId: '14' },
      { name: 'Funeral Services', subId: '14' },
      { name: 'Hair and Beauty', subId: '14' },
      { name: 'Interior Design and Decorative Arts', subId: '14' },
      { name: 'Landscaping Services', subId: '14' },
      { name: 'Laundromats and Dry Cleaners', subId: '14' },
      { name: 'Pet Care', subId: '14' },
      { name: 'Photography', subId: '14' },
      { name: 'Mechanics and Service Centers', subId: '14' },
      { name: 'Auto and Home Paint Job', subId: '14' },
      { name: 'Water Treatment', subId: '14' },

      {
        name: 'Home and Office',
        parentId: '15',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535555/wkn1t77oc8hle9bnljcx.png',
      },
      { name: 'Furniture - Home', subId: '15' },
      { name: 'Beds and Bedding', subId: '15' },
      { name: 'Couches and Dining', subId: '15' },
      { name: 'Home Security and Safety', subId: '15' },
      { name: 'Household Cleaners and Scents', subId: '15' },
      { name: 'Laundry Care', subId: '15' },
      { name: 'Gardening Supplies and Equipment', subId: '15' },
      { name: 'Pest Control Products', subId: '15' },
      { name: 'Office Supplies and Equipment', subId: '15' },
      { name: 'Stationery and Greeting Cards', subId: '15' },
      { name: 'Furniture – Office', subId: '15' },
      { name: 'Office Chairs and Tables', subId: '15' },
      { name: 'Home and Office Fittings', subId: '15' },
      {
        name: 'TV and Radio Broadcasting',
        parentId: '16',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535606/usou3colxzlpvjhnvlj3.png',
      },
      { name: 'Broadcast Entertainment', subId: '16' },
      { name: 'Radio Broadcasting', subId: '16' },
      { name: 'Cable Television', subId: '16' },
      { name: 'Film and Motion Pictures', subId: '16' },
      {
        name: 'Telecommunications and Networks',
        parentId: '17',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535710/q9dv3nfcpfkhpnyllxah.png',
      },
      { name: 'Broadband', subId: '17' },
      { name: 'Enterprise Mobility Management', subId: '17' },
      { name: 'Home and Mobile Networks', subId: '17' },
      { name: 'Networking Equipment', subId: '17' },
      { name: 'VoIP and Videoconferencing', subId: '17' },
      { name: 'Wireless Telecommunications', subId: '17' },
      {
        name: 'Publishing and Printing',
        parentId: '18',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535797/xmkhhvwamrmefkizdey7.png',
      },
      { name: 'Magazines and Periodicals', subId: '18' },
      { name: 'Newspapers', subId: '18' },
      {
        name: 'Cosmetics',
        parentId: '19',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535860/zmlbqxqn1hsddgmubume.png',
      },
      { name: 'Personal Care Products', subId: '19' },
      { name: 'Baby Care Products', subId: '19' },
      { name: 'Feminine Hygiene Products', subId: '19' },
      { name: 'Fragrances and Deodorants', subId: '19' },
      { name: 'Hair Care', subId: '19' },
      { name: "Men's Grooming", subId: '19' },
      { name: "Women's Grooming", subId: '19' },
      { name: 'Oral Care Products', subId: '19' },
      { name: 'Skin Care Products', subId: '19' },
      { name: 'Soap, Bath and Shower', subId: '19' },
      {
        name: 'Sporting Goods and Equipment',
        parentId: '20',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623535937/hwyu59wkof7mbwi9j2ny.png',
      },
      { name: 'Angling and Hunting', subId: '20' },
      { name: 'Bikes and Cycling', subId: '20' },
      { name: 'Golfing', subId: '20' },
      { name: 'Soccer', subId: '20' },
      { name: 'Tennis and Racket Sport', subId: '20' },
      { name: 'Workout attire and Equipment', subId: '20' },
      { name: 'Toys', subId: '20' },
      { name: 'Hiking', subId: '20' },
      {
        name: 'Travel and Tourism',
        parentId: '21',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536029/b7slz1bwtody9otfepwt.png',
      },
      { name: 'Private Jets', subId: '21' },
      { name: 'Commercial Jets', subId: '21' },
      { name: 'Ground Travel – Commercial', subId: '21' },
      { name: 'Ground Travel – VIP', subId: '21' },
      { name: 'Hotels and Shortlets', subId: '21' },
      {
        name: 'Energy and Natural Resources',
        parentId: '22',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536069/r3ip4oombzwm9jkls76f.png',
      },
      { name: 'Biofuels', subId: '22' },
      { name: 'Combined Heat and Power', subId: '22' },
      { name: 'Electricity and Generators', subId: '22' },
      { name: 'Smart Grid', subId: '22' },
      { name: 'Energy Maps', subId: '22' },
      { name: 'Energy Storage', subId: '22' },
      { name: 'Battery Technology', subId: '22' },
      { name: 'Fuel Cells', subId: '22' },
      { name: 'Environmental', subId: '22' },
      { name: 'Air Purification', subId: '22' },
      { name: 'Carbon Emissions and Capture', subId: '22' },
      { name: 'Fossil Fuels', subId: '22' },
      { name: 'Coal', subId: '22' },
      { name: 'Gas', subId: '22' },
      { name: 'LNG (Liquefied Natural Gas)', subId: '22' },
      { name: 'LPG (Liquefied Petroleum Gas)', subId: '22' },
      { name: 'Natural Gas', subId: '22' },
      { name: 'Oil', subId: '22' },
      { name: 'Gasoline and Diesel', subId: '22' },
      { name: 'Oilfield Equipment and Services', subId: '22' },
      { name: 'Pipelines', subId: '22' },
      { name: 'Nuclear Power', subId: '22' },
      { name: 'Renewable Energy', subId: '22' },
      { name: 'Geothermal Energy', subId: '22' },
      { name: 'Hydro Power', subId: '22' },
      { name: 'Solar Power', subId: '22' },
      { name: 'Photovoltaics', subId: '22' },
      { name: 'Wind Power', subId: '22' },
      { name: 'Mining', subId: '22' },
      {
        name: 'Agriculture',
        parentId: '23',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536106/tzclvrpojrbry47a8nrr.png',
      },
      { name: 'Livestock', subId: '23' },
      { name: 'Fishery', subId: '23' },
      { name: 'Animal Feeds', subId: '23' },
      { name: 'Aquaculture', subId: '23' },
      { name: 'Crop Farming', subId: '23' },
      { name: 'Seeds', subId: '23' },
      { name: 'Animal and Crop Health', subId: '23' },
      {
        name: 'Beverages',
        parentId: '24',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536388/tkhkyropxi2ewrzlfv4y.png',
      },
      { name: 'Beer', subId: '24' },
      { name: 'Brandy', subId: '24' },
      { name: 'Cider', subId: '24' },
      { name: 'Spirits', subId: '24' },
      { name: 'Gin', subId: '24' },
      { name: 'Rum', subId: '24' },
      { name: 'Tequila', subId: '24' },
      { name: 'Vodka', subId: '24' },
      { name: 'Whiskey', subId: '24' },
      { name: 'Wine', subId: '24' },
      { name: 'Bottled Water', subId: '24' },
      { name: 'Non alcoholic', subId: '24' },
      { name: 'Sport, Energy', subId: '24' },

      {
        name: 'Food and Nutrition',
        parentId: '25',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536426/dajnvze53pvbxya531od.png',
      },
      { name: 'Grocery', subId: '25' },
      { name: 'Food items', subId: '25' },
      { name: 'Baby Food', subId: '25' },
      { name: 'Canned Food', subId: '25' },
      { name: 'Cereals, Grains and Pulses', subId: '25' },
      { name: 'Condiments and Dressings', subId: '25' },
      { name: 'Dairy Products', subId: '25' },
      { name: 'Fast Food and Take Out', subId: '25' },
      { name: 'Fish and Seafood', subId: '25' },
      { name: 'Frozen Food', subId: '25' },
      { name: 'Fruit and Vegetables', subId: '25' },
      { name: 'Health Food and Sports Nutrition', subId: '25' },
      { name: 'Weight Loss', subId: '25' },
      { name: 'Meat, Poultry and Eggs', subId: '25' },
      { name: 'Nuts, Seeds and Dried Fruit', subId: '25' },
      { name: 'Oils and Fats', subId: '25' },
      { name: 'Organic Foods', subId: '25' },
      { name: 'Pet Food', subId: '25' },
      { name: 'Tobacco and Cigarettes', subId: '25' },

      {
        name: ' Food and Kitchen Equipment',
        parentId: '26',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536470/saxocic1sxrprz6sw4oy.png',
      },
      { name: 'Kitchen Utensils', subId: '26' },
      { name: 'Kitchen and Food Processing', subId: '26' },
      { name: 'Vending Machines', subId: '26' },
      {
        name: 'Healthcare',
        parentId: '27',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536498/leedwptavhrizslej4bi.png',
      },
      { name: 'Animal Healthcare/Veterinary', subId: '27' },
      { name: 'Blood Banking', subId: '27' },
      { name: 'Dental', subId: '27' },
      { name: 'E-Healthcare and Diagnostics', subId: '27' },
      { name: 'Hospital Information Systems', subId: '27' },
      { name: 'Optical', subId: '27' },
      { name: 'Alternative and Complementary Medicine', subId: '27' },
      { name: 'Intensive Care and Emergency', subId: '27' },
      { name: 'Maternal and Neonatal', subId: '27' },
      { name: "Women's Health", subId: '27' },
      { name: 'Wound Care', subId: '27' },
      {
        name: 'Medical Devices, Aid and Implant',
        parentId: '28',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536546/ij6yocklemn1pdke1xvq.png',
      },
      { name: 'Dialysis', subId: '28' },
      { name: 'ENT Devices', subId: '28' },
      { name: 'Hearing Aids and Implants', subId: '28' },
      { name: 'Hospital Disposables', subId: '28' },
      { name: 'Magnetic Resonance Imaging', subId: '28' },
      { name: 'Mammography', subId: '28' },
      { name: 'Radiography', subId: '28' },
      { name: 'Ultrasound', subId: '28' },
      { name: 'Needles and Syringes', subId: '28' },
      { name: 'Orthopedic Devices', subId: '28' },
      { name: 'Patient Monitoring Equipment', subId: '28' },
      { name: 'Respiratory Devices', subId: '28' },
      { name: 'Surgical Devices', subId: '28' },
      { name: 'Wheelchairs and Mobility Aids', subId: '28' },
      {
        name: 'Pharmaceuticals and OTC Drugs',
        parentId: '29',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536592/bldoaaig3tms67xpkpog.png',
      },
      { name: 'Anesthetic Drugs', subId: '29' },
      { name: 'Animal Pharmaceuticals', subId: '29' },
      { name: 'Health and Wellness', subId: '29' },
      { name: 'Antibiotics', subId: '29' },
      { name: 'Addiction Disorders Drugs', subId: '29' },
      { name: 'Immune Disorders Drugs', subId: '29' },
      { name: 'Allergy Drugs', subId: '29' },
      { name: 'Immunosuppressive Drugs', subId: '29' },
      { name: 'Infectious Diseases Drugs', subId: '29' },
      { name: 'Mental Disorders Drugs', subId: '29' },
      { name: 'Anxiety Drugs', subId: '29' },
      { name: 'Respiratory Drugs', subId: '29' },
      { name: 'Sexual and Reproductive Health Drugs', subId: '29' },
      { name: 'Oncology Drugs', subId: '29' },
      { name: 'Over the Counter (OTC) Drugs', subId: '29' },
      { name: 'Cough and Cold Drugs', subId: '29' },
      { name: 'Pharmaceutical Manufacturing', subId: '29' },
      { name: 'Vitamins and Dietary Supplements', subId: '29' },
      {
        name: ' Books',
        parentId: '30',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536744/bv5kykqnn1r7v7axn6wk.png',
      },
      { name: 'Science Books', subId: '30' },
      { name: 'Humanities Books', subId: '30' },
      { name: 'Political Science', subId: '30' },
      { name: 'Psychology', subId: '30' },
      { name: 'Society and Social Sciences', subId: '30' },
      { name: 'Sociology', subId: '30' },
      { name: 'Industry Standards', subId: '30' },
      { name: 'Sex and Romance', subId: '30' },
      { name: 'Other books', subId: '30' },
      {
        name: 'Building and Construction',
        parentId: '31',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536772/orpdu3nhzrsksorgluu9.png',
      },
      { name: 'Building Materials', subId: '31' },
      { name: 'Cement Brick and Concrete', subId: '31' },
      { name: 'Doors and Windows', subId: '31' },
      { name: 'Flooring Stone and Tile', subId: '31' },
      { name: 'Elevators and Escalators', subId: '31' },
      { name: 'Fire Protection Materials and Devices', subId: '31' },
      { name: 'Hand Tools', subId: '31' },
      { name: ' Heavy Machinery', parentId: '32' },
      { name: 'Cranes and Lifting Equipment', subId: '32' },
      { name: 'Excavation and Earthmoving Equipment', subId: '32' },
      { name: 'Road Construction Equipment', subId: '32' },
      { name: 'HVAC', subId: '32' },
      { name: 'MEMS', subId: '32' },
      { name: '3D Printing', subId: '32' },
      { name: 'Heat Exchangers and Cooling Towers', subId: '32' },
      { name: 'Industrial Ovens', subId: '32' },
      { name: 'Industrial Refrigeration', subId: '32' },
      { name: 'Mining Equipment', subId: '32' },
      { name: 'Logistics', parentId: '33' },
      { name: 'Parcel', subId: '33' },
      { name: 'Trucking', subId: '33' },
      { name: 'Industrial Logistics', subId: '33' },
      {
        name: 'Machinery',
        parentId: '34',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536810/hm4qbji7fcthvttt3zmr.png',
      },
      { name: 'Agricultural Machinery and Equipment', subId: '34' },
      { name: 'Forestry Machinery and Equipment', subId: '34' },
      { name: 'Industrial Machinery', subId: '34' },
      { name: 'Textile Machinery', subId: '34' },
      { name: 'Machine Parts', subId: '34' },
      { name: 'Machine Tools', subId: '34' },
      { name: 'Turbines', subId: '34' },
      { name: 'Conveyors', subId: '34' },
      { name: 'Forklifts', subId: '34' },
      { name: 'ATMs', subId: '34' },
      {
        name: 'Military Aerospace and Defense',
        parentId: '35',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623536921/jbfbk4xxgulruwwvn4ip.png',
      },
      { name: 'Ammunition', subId: '35' },
      { name: 'Biodefense', subId: '35' },
      { name: 'C4ISR', subId: '35' },
      { name: 'Homeland Defense', subId: '35' },
      { name: 'Infantry Weapons and Equipment', subId: '35' },
      { name: 'Military Aircraft', subId: '35' },
      { name: 'Military Logistics', subId: '35' },
      { name: 'Military Unmanned Systems', subId: '35' },
      { name: 'Missiles', subId: '35' },
      { name: 'Naval Vessels', subId: '35' },
      { name: 'Radar Systems', subId: '35' },
      { name: 'Tanks and Armored Vehicles', subId: '35' },
      {
        name: 'Machine Learning Data and Security',
        parentId: '36',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537177/hvdy4wlpln4sbg5tetmp.png',
      },
      { name: 'Biometrics Devices', subId: '36' },
      { name: 'Processing Units', subId: '36' },
      { name: 'Supercomputers', subId: '36' },
      { name: 'IT Security', subId: '36' },
      { name: 'Nanotechnology', subId: '36' },
      { name: 'Lasers', subId: '36' },
      { name: 'LED and OLED', subId: '36' },
      { name: 'Equipment – Point of Sale', subId: '36' },
      { name: 'RFID', subId: '36' },
      { name: 'Contactless Payments', subId: '36' },
      { name: 'NFC', subId: '36' },
      { name: 'Robotics', subId: '36' },
      { name: 'Semiconductor', subId: '36' },
      { name: 'Sensors', subId: '36' },
      { name: 'Software', subId: '36' },
      { name: 'Video Surveillance', subId: '36' },
      { name: 'Virtual and Augmented Reality', subId: '36' },
      { name: 'Big Data Analytics', subId: '36' },
      { name: 'Cloud Computing and Storage', subId: '36' },
      { name: 'Call and Data Centers', subId: '36' },
      { name: 'Blockchain', subId: '36' },
      {
        name: 'Graphics and Design',
        parentId: '37',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537284/z8ycgzqs3tct1qtr3rh9.png',
      },
      { name: 'Logo and Brand Identity', subId: '37' },
      { name: 'Brand Style Guides', subId: '37' },
      { name: 'Business Cards and Stationery', subId: '37' },
      { name: 'Pattern Design', subId: '37' },
      { name: 'Tattoo Design', subId: '37' },
      { name: 'Portraits and Caricatures', subId: '37' },
      { name: 'Cartoons and Comics', subId: '37' },
      { name: 'Storyboards', subId: '37' },
      { name: 'Visual Design', subId: '37' },
      { name: 'Presentation Design', subId: '37' },
      { name: 'Infographic Design', subId: '37' },
      { name: 'Resume Design', subId: '37' },
      { name: 'Vector Tracing', subId: '37' },
      { name: 'Packaging and Labels', subId: '37' },
      { name: 'Album Cover Design', subId: '37' },
      { name: 'Podcast Cover Art', subId: '37' },
      { name: 'Packaging Design', subId: '37' },
      { name: 'Car Wraps', subId: '37' },
      { name: 'Brochure Design', subId: '37' },
      { name: 'Signage Design', subId: '37' },
      { name: 'Poster Design', subId: '37' },
      { name: 'Catalog Design', subId: '37' },
      { name: 'Menu Design', subId: '37' },
      { name: 'Postcard Design', subId: '37' },
      { name: 'Invitation Design', subId: '37' },
      { name: 'Merchandise', subId: '37' },
      { name: 'Game Design', subId: '37' },
      { name: 'Game Character Design', subId: '37' },
      {
        name: 'Architecture, Industrial, Product Design',
        parentId: '38',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537332/mqoca7mqjjljpzjz40go.png',
      },
      { name: 'Architecture and Interior Design', subId: '38' },
      { name: 'Landscape Design', subId: '38' },
      { name: 'Building Information Modeling', subId: '38' },
      { name: 'Trade Booth Design', subId: '38' },
      { name: 'Product and Characters Design', subId: '38' },
      { name: 'Character Modeling', subId: '38' },
      { name: 'AR/VR Design', subId: '38' },
      { name: '2D Drawing and Floor Plans', subId: '38' },
      { name: '3D Modeling and Rendering', subId: '38' },
      { name: 'Virtual Staging', subId: '38' },
      { name: 'Diagrams and Mapping', subId: '38' },
      { name: 'BIM 3D Modeling', subId: '38' },
      { name: 'BIM Family Creation', subId: '38' },
      {
        name: 'Content Writing and Translation',
        parentId: '39',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537362/o2nmapv810qycsixstxh.png',
      },
      { name: 'Articles and Blog Posts', subId: '39' },
      { name: 'Translation', subId: '39' },
      { name: 'Proofreading and Editing', subId: '39' },
      { name: 'Resume Writing', subId: '39' },
      { name: 'Cover Letters', subId: '39' },
      { name: 'LinkedIn Profiles', subId: '39' },
      { name: 'Podcast Writing', subId: '39' },
      { name: 'White Papers', subId: '39' },
      { name: 'Case Studies', subId: '39' },
      { name: 'Sales Copy', subId: '39' },
      { name: 'Press Releases', subId: '39' },
      { name: 'Social Media Copy', subId: '39' },
      { name: 'Transcripts', subId: '39' },
      { name: 'Research and Summaries', subId: '39' },
      { name: 'Book and eBook Writing', subId: '39' },
      { name: 'Book Editing', subId: '39' },
      { name: 'Beta Reading', subId: '39' },
      { name: 'Website Content', subId: '39' },
      { name: 'Product Descriptions', subId: '39' },
      { name: 'Grant Writing', subId: '39' },
      { name: 'Technical Writing', subId: '39' },
      { name: 'Business Names and Slogans', subId: '39' },
      { name: 'Scriptwriting', subId: '39' },
      { name: 'Email Copy', subId: '39' },
      { name: 'Speechwriting', subId: '39' },
      { name: 'Creative Writing', subId: '39' },
      {
        name: 'Video and Game Editing',
        parentId: '40',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537389/sukyszawbopuz1kdnsfb.png',
      },
      { name: 'Video Editing', subId: '40' },
      { name: 'Short Video Ads', subId: '40' },
      { name: 'Lyric and Music Videos', subId: '40' },
      { name: 'Animated GIFs', subId: '40' },
      { name: 'Logo Animation', subId: '40' },
      { name: 'Intros and Outros', subId: '40' },
      { name: 'App and Website Previews', subId: '40' },
      { name: 'Character Animation', subId: '40' },
      { name: '3D Product Animation', subId: '40' },
      { name: 'Animation for Kids', subId: '40' },
      { name: 'Animation for Streamers', subId: '40' },
      { name: 'Live Action Explainers', subId: '40' },
      { name: 'eLearning Video Production', subId: '40' },
      { name: 'Spokespersons Videos', subId: '40' },
      { name: 'Unboxing Videos', subId: '40' },
      { name: 'Visual Effects', subId: '40' },
      { name: 'Article to Video', subId: '40' },
      { name: 'Subtitles and Captions', subId: '40' },
      { name: 'Screencasting Videos', subId: '40' },
      { name: 'Slideshows Videos', subId: '40' },
      { name: 'Book Trailers', subId: '40' },
      { name: 'Game Trailers', subId: '40' },
      { name: 'Real Estate Promos', subId: '40' },
      { name: 'Video on Demand', subId: '40' },
      { name: 'Video, DVD and Blu-ray', subId: '40' },
      {
        name: 'Voice, Production and Music',
        parentId: '41',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537419/fpvhsvhjcm98sbdhnjb5.png',
      },
      { name: 'Brand Voice and Tone', subId: '41' },
      { name: 'Producers and Composers', subId: '41' },
      { name: 'Singers and Vocalists', subId: '41' },
      { name: 'Mixing and Mastering', subId: '41' },
      { name: 'Online Language Lessons', subId: '41' },
      { name: 'Session Musicians', subId: '41' },
      { name: 'Online Music Lessons', subId: '41' },
      { name: 'Podcast Editing', subId: '41' },
      { name: 'Songwriters', subId: '41' },
      { name: 'Audiobook Production', subId: '41' },
      { name: 'Audio Ads Production', subId: '41' },
      { name: 'Jingles and Intros', subId: '41' },
      { name: 'DJ Drops and Tags', subId: '41' },
      { name: 'Dialogue Editing', subId: '41' },
      { name: 'Music Transcription', subId: '41' },
      { name: 'Sound Effects', subId: '41' },
      { name: 'Vocal Tuning', subId: '41' },
      {
        name: 'Web, App and Game Development',
        parentId: '42',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537455/mnvcq1ufdaesxmezcqaa.png',
      },
      { name: 'Website Builders and CMS', subId: '42' },
      { name: 'Web Programming', subId: '42' },
      { name: 'E-Commerce Development', subId: '42' },
      { name: 'Mobile Apps', subId: '42' },
      { name: 'Desktop Applications', subId: '42' },
      { name: 'Game Development', subId: '42' },
      { name: 'Development for Streamers', subId: '42' },
      {
        name: 'IT Support',
        parentId: '43',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537511/bg3hsu2zri2vfbhtxz8f.png',
      },
      { name: 'Chatbots', subId: '43' },
      { name: 'Online Coding Lessons', subId: '43' },
      { name: 'Cybersecurity and Data Protection', subId: '43' },
      { name: 'Data Analysis and Reports', subId: '43' },
      { name: 'Convert Files', subId: '43' },
      { name: 'Databases', subId: '43' },
      { name: 'User Testing', subId: '43' },
      { name: 'Quality Assurance testing', subId: '43' },
      {
        name: 'SEO',
        parentId: '44',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537578/zfhoo8wxwxkx6fysborn.png',
      },
      { name: 'Email Marketing', subId: '44' },
      { name: 'Lead Generation', subId: '44' },
      { name: 'Promote Your Listings', subId: '44' },
      { name: 'Social Media Marketing', subId: '44' },
      { name: 'Online Store', subId: '44' },
      { name: 'Website Creation', subId: '44' },
      { name: 'Website Design', subId: '44' },
      { name: 'Website Content', subId: '44' },
      { name: 'Technical SEO', subId: '44' },
      { name: 'Flyer Distribution', subId: '44' },
      { name: 'Viral Videos', subId: '44' },
      {
        name: 'Consulting',
        parentId: '45',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537685/ds3vwwnnoxokzf7lpmz5.png',
      },
      { name: 'E-Commerce Management', subId: '45' },
      { name: 'Virtual Assistant', subId: '45' },
      { name: 'Data Entry', subId: '45' },
      { name: 'Market Research', subId: '45' },
      { name: 'Project Management', subId: '45' },
      { name: 'Career Counseling', subId: '45' },
      { name: 'HR Consulting', subId: '45' },
      { name: 'Business Plans', subId: '45' },
      { name: 'Branding Services', subId: '45' },
      { name: 'Financial Consulting', subId: '45' },
      { name: 'Business Consulting', subId: '45' },
      { name: 'Marketing Strategy', subId: '45' },
      { name: 'Social Media Marketing', subId: '45' },
      { name: 'Digital Marketing', subId: '45' },
      { name: 'Presentations', subId: '45' },
      { name: 'Outsourcing', subId: '45' },
      { name: 'Franchise', subId: '45' },
      { name: 'Leasing', subId: '45' },
      { name: 'Bankruptcy', subId: '45' },
      { name: 'Commercial Law', subId: '45' },
      { name: 'Construction Law', subId: '45' },
      { name: 'Criminal Law', subId: '45' },
      { name: 'Employment Law', subId: '45' },
      { name: 'Human Rights Law', subId: '45' },
      { name: 'Intellectual Property', subId: '45' },
      { name: 'Patents', subId: '45' },
      { name: 'International Law', subId: '45' },
      { name: 'Medical Law', subId: '45' },
      { name: 'Property Law', subId: '45' },
      { name: 'Property', subId: '45' },
      { name: 'Agents and Brokers', subId: '45' },
      { name: 'Blockchain and Cryptocurrency', subId: '45' },
      {
        name: 'Online Lessons',
        parentId: '46',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537753/yc4gu2b9ehce03xtof9h.png',
      },
      { name: 'Fitness Lessons', subId: '46' },
      { name: 'Craft Lessons', subId: '46' },
      { name: 'Cooking Lessons', subId: '46' },
      { name: 'Arts and Crafts', subId: '46' },
      { name: 'Relationship Advice', subId: '46' },
      { name: 'Health, Nutrition and Fitness', subId: '46' },
      { name: 'Astrology and Readings', subId: '46' },
      { name: 'Spiritual and Healing', subId: '46' },
      { name: 'Family and Genealogy', subId: '46' },
      { name: 'Gaming', subId: '46' },
      { name: 'Collectibles', subId: '46' },
      { name: 'Traveling tips', subId: '46' },
      {
        name: 'Gaming',
        parentId: '47',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537879/h1spylwy7akg1acicrrv.png',
      },
      { name: 'User Testing', subId: '47' },
      {
        name: 'Influencers',
        parentId: '48',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623537940/ugygskp5p1ozqjzaear6.png',
      },
      { name: 'Web and Blog Services', subId: '48' },
      { name: 'YouTube Services', subId: '48' },
      { name: 'Instagram Services', subId: '48' },
      { name: 'Facebook Services', subId: '48' },
      { name: 'Twitter Services', subId: '48' },
      { name: 'Celebrity Impersonators', subId: '48' },
      {
        name: 'Manufacturing',
        parentId: '49',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623538005/fip0zpwh07klr25jdv0y.png',
      },
      { name: 'Clothing and Textiles', subId: '49' },
      { name: 'Petroleum, Chemicals and Plastics', subId: '49' },
      { name: 'Electronics, Computers and Transportation', subId: '49' },
      { name: 'Food Production', subId: '49' },
      { name: 'Metal Manufacturing', subId: '49' },
      { name: 'Wood, Leather and Paper', subId: '49' },
      {
        name: 'S.A.D',
        parentId: '50',
        displayImage:
          'https://res.cloudinary.com/spottr/image/upload/v1623538063/ngguugbfuxdhb4fqqaxx.png',
      },
      { name: 'Escorts', subId: '50' },
      { name: 'Adult toys', subId: '50' },
      { name: 'Adult content', subId: '50' },
    ];

    const parents = [];
    const children = [];
    let parentId: string;
    for (const item of data) {
      if (item.parentId) {
        delete item.parentId;
        parentId = uuidv4();
        parents.push({
          id: parentId,
          ...item,
          description: item.name,
          slug: Helper.slugify(item.name),
        });
      } else if (item.subId) {
        delete item.subId;
        parents.push({
          ...item,
          id: uuidv4(),
          parentId,
          isSubcategory: true,
          description: item.name,
          slug: Helper.slugify(item.name),
        });
      }
    }

    return { parents, children };
  }
}
